version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
